# Generated by Django 4.2.1 on 2023-07-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_courses_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideoCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvideo', to='content.courses')),
            ],
        ),
    ]
