# Generated by Django 4.2.1 on 2023-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_uploadvideocourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideocourses',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
