# Generated by Django 4.2.1 on 2023-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('auther', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='singlevideos/')),
                ('body', models.TextField()),
            ],
        ),
    ]
