# Generated by Django 4.2.1 on 2023-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_tag_singlevideo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlevideo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
