# Generated by Django 4.2.1 on 2023-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='aticletag', to='content.articletag'),
        ),
    ]
