# Generated by Django 4.2.1 on 2023-07-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_articletag_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideocourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qu', to='content.courses'),
        ),
    ]
